### ISSUE TITLE
float64 can't convert to Int

### ISSUE THREAD

**Issue by lqu3j** [jackc/pgtype#60] opened 2020-09-29 04:44 UTC
i use gorm , code like follow:
```go
       a := float64(1)
	demo := Demo{}
	if err := db.Where("id = ?", a).Find(&demo); err != nil {
		t.Fatal(err)
	}
```
gorm print SQL log:
```SQL
SELECT * FROM "demos" WHERE id = 1.000000 AND "demos"."deleted_at" IS NULL
```

error: **cannot convert 1 to Int4**

is a bug or not?,  please forgive my poor english!!!

**Comment by jackc** [comment] 2020-10-03 13:41
Well, it's not a bug. It could be considered a missing feature though. To be honest, I'm not a big fan of automatic type conversion when there is possible data loss (e.g. float to int loses fractional numbers), but it looks like SQL already does something like this so I guess it is reasonable to support it here as well.

I merged your PR on pgtype: https://github.com/jackc/pgtype/pull/61

**Closed by jackc** 2020-10-03 13:41 UTC
